# Generated by Django 2.2 on 2019-04-26 14:03

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zebrafish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=20)),
                ('line_number', models.CharField(max_length=20)),
                ('line_type', models.CharField(choices=[('wt', 'WT'), ('tg', 'Tg'), ('mu', 'Mutant'), ('cko', 'CRISPR KO'), ('cki', 'CRISPR KI'), ('other', 'Other')], max_length=5)),
                ('background', models.CharField(max_length=20)),
                ('genotype', models.CharField(max_length=20)),
                ('phenotype', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('availability', models.CharField(choices=[('live', 'Live'), ('cryo', 'Cryopreserved'), ('both', 'Live & Cryopreserved'), ('none', 'Unavailable')], max_length=4)),
                ('comments', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('mta', models.BooleanField(default=False, verbose_name='MTA')),
                ('line_type_other', models.CharField(blank=True, max_length=20, verbose_name='')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'verbose_name_plural': 'zebrafish',
            },
        ),
    ]
