# Generated by Django 2.1.8 on 2019-06-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('fishdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
    ]
