# Generated by Django 2.2.1 on 2019-05-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('fishdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zebrafish',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Ownership'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ZebrafishPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewonly', models.BooleanField(verbose_name='Read only access')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('zebrafish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishdb.Zebrafish')),
            ],
            options={
                'verbose_name': 'Zebrafish permission',
                'verbose_name_plural': 'Zebrafishs permissions',
                'unique_together': {('zebrafish', 'group')},
            },
        ),
    ]
