# Generated by Django 2.2.1 on 2019-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0002_auto_20190506_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zebrafish',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='zebrafish',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
