# Generated by Django 2.1.8 on 2019-06-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0002_fish_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
    ]
