# Generated by Django 2.1.8 on 2019-06-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0003_auto_20190610_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'line',
                'verbose_name_plural': 'lines',
                'ordering': ['name'],
            },
        ),
    ]
