# Generated by Django 2.1.8 on 2019-06-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0004_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='line_type',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='line_type_other',
        ),
    ]
