# Generated by Django 2.1.8 on 2019-06-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0006_fish_line_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Line',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='line_type',
            new_name='category',
        ),
    ]
