# Generated by Django 2.1.8 on 2019-06-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0008_auto_20190610_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='common_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
