# Generated by Django 2.1.8 on 2019-06-10 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fishdb', '0009_fish_common_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='owner',
            new_name='maintainer_group',
        ),
        migrations.AddField(
            model_name='fish',
            name='maintainer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
