# Generated by Django 2.1.8 on 2019-06-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0010_auto_20190610_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='maintainer_user',
            new_name='maintainer',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='maintainer_group',
            new_name='ownership',
        ),
    ]
