# Generated by Django 2.1.8 on 2019-06-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0012_auto_20190610_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='line_description',
            field=models.TextField(blank=True),
        ),
    ]
