# Generated by Django 2.1.8 on 2019-06-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0015_auto_20190617_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='background',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fish',
            name='genotype',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='fish',
            name='phenotype',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
