# Generated by Django 2.1.8 on 2019-06-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0016_auto_20190617_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='line_name',
            new_name='strain_name',
        ),
    ]
