# Generated by Django 2.1.8 on 2019-07-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0017_auto_20190617_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public through Congento'),
        ),
    ]
