# Generated by Django 2.1.8 on 2019-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0018_auto_20190710_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='background',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fish',
            name='genotype',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fish',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='origin',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='fish',
            name='phenotype',
            field=models.CharField(max_length=30),
        ),
    ]
