# Generated by Django 2.1.8 on 2019-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0019_auto_20190710_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='mta',
            field=models.BooleanField(default=True, verbose_name='MTA'),
        ),
    ]
