# Generated by Django 2.1.8 on 2019-07-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0020_auto_20190710_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='origin',
            field=models.CharField(blank=True, max_length=80, verbose_name='Imported from'),
        ),
    ]
