# Generated by Django 2.1.8 on 2019-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0022_remove_fish_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='quarantine',
            field=models.BooleanField(default=False, verbose_name='Quarantine'),
        ),
    ]
