# Generated by Django 2.1.8 on 2019-07-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0023_fish_quarantine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Group'),
        ),
    ]
