# Generated by Django 2.1.11 on 2019-08-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0024_auto_20190711_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='origin',
            field=models.CharField(blank=True, help_text='Leave blank for in-house generated lines', max_length=80, verbose_name='Imported from'),
        ),
    ]
