# Generated by Django 2.2.11 on 2021-03-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishdb', '0026_auto_20190910_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={'permissions': [('can_import', 'Can import from XLSX')], 'verbose_name': 'fish', 'verbose_name_plural': 'fish'},
        ),
    ]
